name: Hangar Publish
on:
  release:
    types: [ prereleased, released ]
jobs:
  build:
    env:
      HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Publish with Gradle to Hangar
        uses: gradle/actions/setup-gradle@v4
        with: ./gradlew publishAllPublicationsToHangar